---
dist: bionic
language: ruby
cache: bundler
before_install:
  - yes | gem update --system
  - bundle --version
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=centos6-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=centos6-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=centos7-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=centos7-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian8-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian8-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian9-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian9-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian10-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian10-64 CHECK=beaker
    services: docker
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  webhooks: https://voxpupu.li/incoming/travis
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "aK1I5ctuuB7eGuaOUT/pJRB3U/L1chtiA18a2WDmRXYX/5mvryqNFAm/64oxxOeXmALbjAmMacDW2jMMDJcU6ZVm5i/V7D4wfa/rcTZxUCwxspa4yhWba1c/NGzElz201NKWHscHhY657egC0iIUe8PERSrGQpFPi2RyuAcOfyH+46cP7iuJUPsa5jIF8E2eyMnaQOhuyjBH+XYsH5q1xzpfCJCpCoqagmyJXTcdrYpNGTEux7bc2N+bLEWnjK+Rlhvgnq+D1xK/uCtKv2yLd+ackgSPbtGJ52xWMpJKyutgzzgEMaNakK91TkZJuZg9esQXmiHbuj/gx5to+JKXWN/yfK4Jm91HetOcd0azPysszmcQnQdRa3S2fbafBsqvvyjnGFtCOdI7T9CN0kzcKJZlgsqOE8a+TwuSn+fHdFZB99XXpk/cd+hyn3NfZPXYJtmq3hEwxYVytd7wqPvNvvBULZW+nGrQ6TI2lQ7Hf5hy/kWoKT9MB1PiZRfwEaTfNM88nUTl+Wabnb2dGtsZuty1KiOEHRySLnX1SCjl7Mbb0uxQc2lmj9Z8vQFp7WEPspQemNs6Byz/pYIUytjSwo7Z+oRc56VMf/T27DqGDSGjC7wzPsOZGF8r0D/cQ8Iziyd9F9/dqs00DDV5l7C3Q8qpg4JIN8ZgTfucgQvkO8k="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
